"""empty message

Revision ID: 27f306eec67a
Revises: 1859f704d476
Create Date: 2023-08-23 17:38:38.989890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f306eec67a'
down_revision = '1859f704d476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('follower_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'follower', ['follower_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('follower_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
