"""empty message

Revision ID: 398d84ed3eb4
Revises: 27f306eec67a
Create Date: 2023-08-23 17:42:58.053454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398d84ed3eb4'
down_revision = '27f306eec67a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('follower_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('follower_follower_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['follower_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('follower_follower_id_fkey', 'follower', ['follower_id'], ['id'])
        batch_op.alter_column('follower_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
