"""empty message

Revision ID: f8ae8b150840
Revises: 398d84ed3eb4
Create Date: 2023-08-23 17:56:41.633892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ae8b150840'
down_revision = '398d84ed3eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint('follower_follower_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('follower_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('follower_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('follower_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('follower_follower_id_fkey', 'user', ['follower_id'], ['id'])

    # ### end Alembic commands ###
